emp_detail/urls.py
from django.urls import path
from . import views
from django.conf import settings  
from django.conf.urls.static import static 

app_name="emp_detail"

urlpatterns = [
    path('',views.index,name='index'),
    path('list_details',views.list_details,name='list_details'),
    path('add_emp',views.add_emp,name='add_emp'),
    path('display_card',views.display_card,name='display_card'),
    path('display_card/<int:id>',views.display_card,name='display_card'),
    path('logout',views.logout,name='logout'),
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('emp_detail/',include('emp_detail.urls'),name='emp_detail'),
    path('qrcode/',include('qrcode_app.urls'),name='qrcode_app'),
]

qrcode_app/urls.py
from django.urls import path
from . import views

app_name='qrcode'

urlpatterns = [
    path('',views.qrcode,name='qrcode'),
]

emp_detail/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Roles(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Role"
        verbose_name_plural = "Roles"

class Detail(models.Model):
    first_name=models.CharField(max_length=100,null=True)
    last_name=models.CharField(max_length=100,null=True)
    phone = models.IntegerField(default=0)
    telephone_number=models.IntegerField(default=0)
    fax_number=models.IntegerField(default=0)
    email_id=models.EmailField()
    account_created=models.DateField(default=datetime.now)
    image_upload=models.ImageField(upload_to='images',null=True)
    qr_code=models.ImageField(upload_to='qrcode',null=True)
    social_media1=models.CharField(max_length=100,null=True)
    social_media2=models.CharField(max_length=100,null=True)
    address = models.CharField(max_length=200,null=True)
    role=models.ForeignKey(Roles,on_delete=models.CASCADE)
    template_id=models.IntegerField(default=0)

    def __str__(self):
        return "%s %s %s" % (self.first_name, self.last_name,self.email_id)

    class Meta:
        verbose_name="Detail"
        verbose_name_plural = "Details"

qrcode_app/models.py
from django.db import models

# Create your models here.

emp_detail/views.py
# Create your views here.
from django.shortcuts import render,redirect
from .models import Detail
from datetime import datetime
import qrcode
from PIL import Image
from django.core.files.base import ContentFile
from io import BytesIO
import base64
from django.contrib import auth
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required



# Create your views here.
@login_required
def index(request):
    return render(request,'emp/index.html')

@login_required
def list_details(request):
    business_cards = Detail.objects.all()
    #current_image = f"{MEDIA_ROOT}images\{business_cards.image_upload}"
    print("\n \n \n ")
    #print(current_image)
    context={
        'business_cards':business_cards
    }
    return render(request,"list_details.html",context)

@login_required
def add_emp(request):
    if request.method=="POST":
        prod=Detail()
        prod.first_name=request.POST["firstname"]
        prod.last_name=request.POST["lastname"]
        prod.phone=int(request.POST["phone"])
        prod.telephone_number=int(request.POST["telephone"])
        prod.fax_number=int(request.POST["printer"])
        prod.email_id=request.POST["email"]
        prod.social_media1=request.POST["website1"]
        prod.social_media2=request.POST["website2"]
        prod.address=request.POST["address"]
        prod.role_id=int(request.POST["role"])
        prod.account_created=datetime.now()
        prod.template_id = request.POST['template_id']
        if len(request.FILES) != 0: 
            prod.image_upload=request.FILES['image']

            logo = Image.open(request.FILES['image'])
            basewidth = 85

            wpercent = basewidth / float(logo.size[0])
            hsize = int(float(logo.size[1]) * float(wpercent))
            logo = logo.resize((basewidth, hsize), Image.ANTIALIAS)

            qr_big = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_H, box_size=10, border=4)
            qr_big.add_data(request.POST["website1"])
            qr_big.make(fit=True)

            img_qr_big = qr_big.make_image(fill_color="blue", back_color="white").convert("RGB")
            qr_width, qr_height = img_qr_big.size

            logo_width, logo_height = logo.size
            logo_size = min(qr_width, qr_height) // 4

            logo_resized = logo.resize((logo_size, logo_size), Image.ANTIALIAS)
            logo_pos = ((qr_width - logo_size) // 2, (qr_height - logo_size) // 2)
            img_qr_big.paste(logo_resized, logo_pos)

            name=request.POST["firstname"]
            qr_code_buffer=BytesIO()
            img_qr_big.save(qr_code_buffer, format='PNG')
            qr_code_file = ContentFile(qr_code_buffer.getvalue())
            prod.qr_code.save(f"{name}.png", qr_code_file)
         
        prod.save()
        return HttpResponse("Employee added Successfully")
    elif request.method=='GET':
        return render(request,'add_details.html')
    else:
        return HttpResponse("An Exception Occured!Employee has not been Added")
    

@login_required
def display_card(request,id=0):
    selected_template = request.session.get('selected_template')
    if id:
        try:
            emp_details=Detail.objects.get(id=id)
            selected_template = emp_details.template_id
            context={
                'emp_details':emp_details
            }
            return render(request,f'{selected_template}.html',context)
        except:
            return HttpResponse("Something Went wrong")

    return render(request,'display_card.html')

def logout(request):
    auth.logout(request)
    return redirect('home')

portfolio/views.py
from django.shortcuts import render,redirect
from django.contrib import auth,messages

def home(request):
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('emp_detail:index')
        else:
            messages.info(request,"Credentials Invalid")
            return render(request,'home.html')
    else:
        return render(request,'home.html')

qrcode_app/views.py
from django.shortcuts import render



# Create your views here.
def qrcode(request):
    if request.method=="POST":
        param=request.POST['param']
        print(param)
    return render(request,'qrcode/qrcode.html')

templates/add_details.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Office Employee Management System!</title>
  </head>
  <body>
  <div class="container">
    <h1>Add Employee!</h1>
    <hr> 
    <form action="add_emp" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-3">
        <label for="firstname" >First Name:</label>
        <input type="text"  name="firstname" id="firstname" value="{{first_name}}" >
      </div>
      <hr>
      <div class="mb-3">
        <label for="lastname" >Last Name:</label>
        <input type="text"  name="lastname" id="lastname" value="{{last_name}}">
      </div> 
      <hr>
      <div class="mb-3">
        <label for="phone" >Phone Number:</label>
        <input type="number"  name="phone" id="phone" value="{{phone}}">
      </div>
      <hr>
      <div class="mb-3">
        <label for="telephone" >Telephone Number:</label>
        <input type="number"  name="telephone" id="telephone" value="{{telephone}}">
      </div>
      <hr>
      <div class="mb-3">
        <label for="printer" >Printer Number:</label>
        <input type="number"  name="printer" id="printer" value="{{printer}}">
      </div>
      <hr>
      <div class="mb-3">
        <label for="email" >Email ID:</label>
        <input type="email"  name="email" id="email" value="{{email}}">
      </div>
      <hr>
      <div class="mb-3">
        <label for="website1" >Website-1:</label>
        <input type="text"  name="website1" id="website1" value="{{website1}}">
      </div>
      <hr>
      <div class="mb-3">
        <label for="website2" >Website-2:</label>
        <input type="text"  name="website2" id="website2" value="{{website2}}">
      </div>
      <hr>
      <div class="mb-3">
        <label for="role" >Role:</label>
        <input type="number"  name="role" id="role" value="{{role}}">
      </div>
      <hr>
      <div class="mb-3">
        <label for="address" >Address:</label>
        <input type="text"  name="address" id="address" value="{{address}}">
      </div>
      <hr>
      <div class="mb-3">
        <label for="image" >Image:</label>
        <input type="file"  name="image">
      </div>
      <hr>
      <label for="template_id">Select a template:</label>
      <select name="template_id">
        <option value="1">Template 1</option>
        <option value="2">Template 2</option>
        <option value="3">Template 3</option>
        <option value="4">Template 4</option>
      </select>
      <hr>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>


  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/display_card.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="IE=Edge">
    <meta name="theme-color" content="midnightblue">
    <title>Digital Card</title>
    <link rel="shortcut icon" type="image/x-icon" href="#" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href=https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700&family=Source+Sans+Pro:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <body class="theme-one">
      <div class="container">
        <div class="row">
          <div class="col-xl-5 col-md-6 col-sm-10 mx-auto shadow rounded p-0">
            <!-- Profile widget -->
            <div class="card mb-0 shadow rounded overflow-hidden">
              <div class="bg-image">
                <div class="media align-items-end profile-header">
                  <div class="profile mr-3 ">
                    <img src="{% static 'images/logomiddle.png' %}" class="text-center logomiddlemain" />
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <h1 class="text-center name pt-2">{{emp_details.first_name}} {{emp_details.last_name}}</h1><br>
                <p class="p-1 text-center">{{emp_details.role.name}}</p>
              </div>
              <div class="pt-4 pb-1 px-1">
                <div>
                  <div>
                    <span class="row justify-content-center">
                      <a id="download-file" download="vcf/vivek.vcf" href="vcf/vivek.vcf" class="btn btn-lg btn-icon icon-left btn-outline-dark col-6 mt-1 mr-1 "> Save Contact</a>
                      <a data-toggle="modal" data-target="#socialShare" href="#" class="btn btn-lg btn-icon icon-left btn-outline-dark col-4 mt-1  ml-4">
                        <img src="{% static 'images/shareicon.png' %}" width="35">
                      </a>
                      <span></span>
                    </span>
                  </div>
                </div>
              </div>
              <div class=" pt-1  px-4">
                <ul class="contact-details">
                  <li>
                    <span class="address"></span>
                    <span class="leftalign">
                      <a href="#">{{emp_details.address}}</a>
                    </span>
                  </li>
                  <li>
                    <span class="mobile-no"></span>
                    <a href="tel:+91 120 4807100">
                      <span class="leftalign numbertop">+91 {{emp_details.phone}}</a>
                    </span>
                  </li>
                  <li>
                    <span class="printer"></span>
                    <span class="leftalign">
                      <a href="tel:+91 120 4325028"> +91 {{emp_details.fax_number}}</a>
                    </span>
                  </li>
                  <li>
                    <span class="call"></span>
                    <span class="leftalign numbertop">
                      <a href="tel:+91 9654985566">+91 {{emp_details.telephone_number}}</a>
                    </span>
                  </li>
                  <li>
                    <a href="#">
                      <span class="envlope"></span>
                      <span class="leftalign numbertop">
                        <a href="{{emp_details.email_id}}">{{emp_details.email_id}}</a>
                      </span>
                    </a>
                  </li>
                  <li>
                    <span class="weblink"></span>
                    <span class="leftalign">
                      <a href="{{emp_details.social_media1}}" target="_blank">{{emp_details.social_media1}}</a>
                    </span>
                    <a href="{{emp_details.social_media2}}" class="colorlink" target="_blank">{{emp_details.social_media2}}</a>
                  </li>
                </ul>
              </div>
              <div class="pb-2 px-4">
                <div class="row">
                  <div class="col-sm-2 col-2 ">
                    <a href="https://api.whatsapp.com/send/?phone=%2B919654985566" target="_blank" class="media contact-details-item">
                      <img src="{% static 'images/whatsapp.png' %}" />
                    </a>
                  </div>
                  <div class="col-sm-2 col-2 ">
                    <a href="#" class="media contact-details-item">
                      <img src="{% static 'images/facebook.png' %}" />
                    </a>
                  </div>
                  <div class="col-sm-2 col-2 ">
                    <a href="https://www.instagram.com/vivekmalhotra27/?hl=en" target="_blank" class="media contact-details-item">
                      <img src="{% static 'images/insta.png' %}" />
                    </a>
                  </div>
                  <div class="col-sm-2 col-2 ">
                    <a href="https://www.linkedin.com/in/vivek-malhotra-4b90611/" target="_blank" class="media contact-details-item">
                      <img src="{% static 'images/insta.png' %}" />
                    </a>
                  </div>
                  <div class="col-sm-2 col-2 ">
                    <a href="#" class="media contact-details-item">
                      <img src="{% static 'images/youtube.png' %}" />
                    </a>
                  </div>
                  <div class="col-sm-2 col-2 ">
                    <a href="https://twitter.com/VivekMalhotra_" target="_blank" class="media contact-details-item">
                      <img src="{% static 'images/twitter.png' %}" />
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <!-- End profile widget -->
          </div>
        </div>
        <div class="row ">
          <div class="col-xl-5 col-md-6 col-sm-10 mx-auto shadow rounded bgColor p-0">
            <div class="logomiddle ">
              <div class="bg-circle">
                <img src="{% static 'images/logo.png' %}" width="130" class="centerImage">
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xl-5 col-md-6 col-sm-10 mx-auto shadow rounded p-4">
            <div class="row">
              <div class="col-md-3 col-xs-6 col-4 col-lg-2  p-3">
                <img src="{% static 'images/ajjtak.png' %}" class="text-center" />
              </div>
              <div class="ccol-md-3 col-xs-6 col-4 col-lg-2  p-3">
                <img src="{% static 'images/indiatoday.png' %}" class="text-center" />
              </div>
              <div class="col-md-3 col-xs-6 col-4 col-lg-2  p-3 colmin">
                <img class="mr-2" src="{% static 'images/ajtakhd.png' %}" class="text-center" />
              </div>
              <div class="col-md-3 col-xs-6  col-4 col-lg-2 p-3">
                <img src="{% static 'images/news.png' %}" class="text-center" />
              </div>
              <div class="col-md-3 col-xs-6  col-4 col-lg-2  p-3">
                <img src="{% static 'images/itmi.png' %}" class="text-center" />
              </div>
              <div class="col-md-3 col-xs-6  col-4 col-lg-2  p-3">
                <img src="{% static 'images/isque.png' %}" class="text-center" />
              </div>
            </div>
            <div class="col-xl-7 col-md-6 col-sm-10 mx-auto rounded buttoBorder p-0">
              <div class=" text-center p-2 mb-0 border-0">
                <h4 class="pt-3">Scan here</h4>
                <div class="col-md-12 code">
                  <img src="{{emp_details.qr_code.url}}" height="259" width="259" class="text-center qrwidth" />
                </div>
                <div class="col-md-12 my-3">
                  <a download="{{emp_details.qr_code.url}}" href="{{emp_details.qr_code.url}}">
                    <button class="btn btn-icon icon-left btn-outline-dark download_my_qr_code">Download </button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
    </body>
</html>

templates/emp/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Digital Business Card!</title>
  </head>
  <body>
  <div class="container">
    <h1>Welcome to Digital Business card!</h1>
    <a class="btn btn-primary" href="logout" role="button">Log Out</a>
    <hr> 
    <a class="btn btn-primary" href="list_details" role="button">View All Business Card</a>
    <a class="btn btn-primary" href="add_emp" role="button">Add an Employee</a>
    <a class="btn btn-primary" href="{% url 'qrcode:qrcode' %}" role="button">Dynamic QrCode</a>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Welcome to Employee Management System</h1>
    <h2>Login</h2>
    {% for message in messages %}
        <h5>{{ message }}</h5>
    {% endfor %}
    <form action="{% url 'home' %}" method="POST">
        {% csrf_token %}
        <p>Username:</p>
        <input type="text" name="username" class="username" />
        <p>Password:</p>
        <input type="password" name="password" class="password" />
        <br>
        <button type="submit">submit</button>
    </form>
</body>
</html>

templates/list_details.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Digital Business Card!</title>
  </head>
  <body>
  <div class="container">
    <h1>View All Employee Details</h1>
    <hr> 
    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">Sr No.</th>
          <th scope="col">First_name</th>
          <th scope="col">Last_Name</th>
          <th scope="col">Phone Number</th>
          <th scope="col">Account Created</th>
          <th scope="col">Image</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      {% for business_card in business_cards %}
      <tbody>
        <tr>
          <th scope="row">{{business_card.id}}</th>
          <td><a href="display_card/{{business_card.id}}">{{business_card.first_name}}</a></td>
          <td>{{business_card.last_name}}</td>
          <td>{{business_card.phone}}</td>
          <td>{{business_card.account_created}}</td>
          <td>
            <img src="{{business_card.image_upload.url}}" alt="" class="prod-size" height="30px" width="30px">
            <!-- <img src="{MEDIA_ROOT}images\{{ business_card.images.url }}" alt="" class="prod-size"> -->
          </td>
          <td><button type="button" class="btn btn-light"><span class="bi bi-trash"></span></button></td>
        </tr>
      </tbody>
      {% endfor %}
    </table>




  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/qrcode/qrcode.html
<!DOCTYPE html>
<html>
<head>
    <title>Dynamic QR Code Generation</title>
</head>
<body>
    <h1>Dynamic QR Code Generation</h1>
    
    <form action="{% url 'qrcode:qrcode' %}" method="POST">
    {% csrf_token %}
        <input type="text" id="inputData" name="param" placeholder="Enter data">
        <br>
        <button type="submit">Submit</button>
        <div id="qrcodeContainer"></div>
    </form>

    <script src="https://cdn.rawgit.com/davidshimjs/qrcodejs/gh-pages/qrcode.min.js"></script>
    <script>
        var qrCode = new QRCode(document.getElementById("qrcodeContainer"));

        var inputElement = document.getElementById("inputData");
        inputElement.addEventListener("input", function() {
            var inputData = inputElement.value;
            qrCode.clear();
            qrCode.makeCode(inputData);
        });
    </script>
</body>
</html>